"""Offline parser tests against a captured real place ``darray`` fixture.

The fixture is the ``jd[6]`` array from a live ``/maps/preview/place`` RPC
response for "Kim's Island" (the restaurant used in the Apify output example),
regenerated by ``scripts/e2e_google_maps_scraper.py``. These tests pin the
array-index paths so a Google structure shift is caught offline.
"""

import json
from pathlib import Path

import pytest

from app.proprietary.platforms.google_maps.fetch import strip_xssi
from app.proprietary.platforms.google_maps.parsers import (
    brace_match_json,
    dig,
    parse_place,
)

_FIXTURE = Path(__file__).parent / "fixtures" / "place_darray.json"


@pytest.fixture
def darray() -> list:
    return json.loads(_FIXTURE.read_text(encoding="utf-8"))


def test_parse_place_core_fields(darray):
    place = parse_place(darray)
    assert place["title"] == "Kim's Island"
    assert place["placeId"] == "ChIJJQz5EZzKw4kRCZ95UajbyGw"
    assert place["fid"] == "0x89c3ca9c11f90c25:0x6cc8dba851799f09"
    assert place["categoryName"] == "Chinese restaurant"
    assert "Chinese restaurant" in place["categories"]
    assert place["totalScore"] == 4.5
    assert place["phone"] == "(718) 356-5168"
    assert place["website"] == "http://kimsislandsi.com/"
    assert place["plusCode"].startswith("GQ62+8M")


def test_parse_place_address_components(darray):
    place = parse_place(darray)
    assert place["neighborhood"] == "Tottenville"
    assert place["street"] == "175 Main St"
    assert place["city"] == "Staten Island"
    assert place["postalCode"] == "10307"
    assert place["state"] == "New York"
    assert place["countryCode"] == "US"


def test_parse_place_location_and_hours(darray):
    place = parse_place(darray)
    assert place["location"]["lat"] == pytest.approx(40.5107736)
    assert place["location"]["lng"] == pytest.approx(-74.2482624)
    hours = place["openingHours"]
    assert hours and all("day" in h and "hours" in h for h in hours)


def test_parse_place_detail_extras(darray):
    place = parse_place(darray)
    assert place["kgmid"] == "/g/1tmgdcj8"
    # cid = decimal of the fid's second hex half
    assert place["cid"] == str(int("0x6cc8dba851799f09", 16))
    info = place["additionalInfo"]
    assert "Accessibility" in info
    assert {"Wheelchair accessible entrance": True} in info["Accessibility"]
    # every option is a single {name: bool} pair
    for entries in info.values():
        for entry in entries:
            assert len(entry) == 1
            assert all(isinstance(v, bool) for v in entry.values())


def test_parse_place_session_gated_fields(darray):
    # These fields only appear when the RPC is sent with an NID session
    # cookie + the full-page pb selector; the fixture pins that payload.
    place = parse_place(darray)
    dist = place["reviewsDistribution"]
    assert set(dist) == {"oneStar", "twoStar", "threeStar", "fourStar", "fiveStar"}
    assert place["reviewsCount"] == sum(dist.values())
    assert place["imagesCount"] > 0
    assert "All" in place["imageCategories"]
    assert all(u.startswith("https://") for u in place["imageUrls"])
    tags = place["reviewsTags"]
    assert tags and all(
        isinstance(t["title"], str) and isinstance(t["count"], int) for t in tags
    )
    assert len(place["additionalInfo"]) >= 5  # full sections, not just Accessibility


def test_parse_place_hotel_fields():
    # Fixture: live darray for The Plaza (NYC), captured via the detail RPC.
    fixture = Path(__file__).parent / "fixtures" / "hotel_darray.json"
    place = parse_place(json.loads(fixture.read_text(encoding="utf-8")))
    assert place["title"] == "The Plaza"
    assert place["hotelStars"] == "5 stars"
    assert place["checkInDate"] < place["checkOutDate"]  # ISO dates compare
    assert place["hotelDescription"]
    similar = place["similarHotelsNearby"]
    assert len(similar) >= 3
    assert all(h["title"] and h["fid"] for h in similar)
    assert any("hotel" in (h.get("description") or "").lower() for h in similar)
    ads = place["hotelAds"]
    assert ads and all(a["url"].startswith("https://") for a in ads)
    assert any(a.get("price", "").startswith("$") for a in ads)


def test_hotel_fields_absent_for_non_hotels(darray):
    # Kim's Island (restaurant) must not grow hotel fields.
    place = parse_place(darray)
    for key in ("hotelStars", "checkInDate", "similarHotelsNearby", "hotelAds"):
        assert key not in place


def test_popular_times_shapes():
    from app.proprietary.platforms.google_maps.parsers import _popular_times

    darray: list = [None] * 100
    darray[84] = [
        [[7, [[6, 0, "", "None", "6 AM", "No wait", "6a"], [7, 35]]]],
        None,
        None,
        None,
        None,
        None,
        "A little busy",
        [22, 76],
    ]
    out = _popular_times(darray)
    assert out["popularTimesHistogram"] == {
        "Su": [
            {"hour": 6, "occupancyPercent": 0},
            {"hour": 7, "occupancyPercent": 35},
        ]
    }
    assert out["popularTimesLiveText"] == "A little busy"
    assert out["popularTimesLivePercent"] == 76
    assert _popular_times([None] * 100) == {}


def test_parse_place_reservation_links():
    fixture = Path(__file__).parent / "fixtures" / "search_response.json"
    from app.proprietary.platforms.google_maps.fetch import _search_darrays

    jd = json.loads(fixture.read_text(encoding="utf-8"))
    place = parse_place(_search_darrays(jd)[0])
    # the first search hit in the fixture carries a reservation provider
    links = place["tableReservationLinks"]
    assert all(set(link) == {"url", "source"} for link in links)
    assert place["reserveTableUrl"] == links[0]["url"]


def test_parse_place_omits_missing_fields(darray):
    # parse_place drops keys whose path missed, rather than emitting nulls.
    place = parse_place(darray)
    assert all(v is not None for v in place.values())


def test_dig_tolerates_ragged_paths():
    assert dig([1, [2, 3]], 1, 0) == 2
    assert dig([1, [2, 3]], 5) is None
    assert dig([1, None], 1, 0) is None
    assert dig("not a list", 0) is None


def test_strip_xssi_and_brace_match_handle_html_wrapper():
    # Mirrors the real proxy response: text/plain body wrapped in <p>…</p>.
    raw = ')]}\'\n[1,[2,3],"x"]</p></body></html>'
    body = strip_xssi(raw)
    blob = brace_match_json(body, body.index("["))
    assert json.loads(blob) == [1, [2, 3], "x"]

    wrapped = '<html><body><p>)]}\'\n[["a"]]'
    assert strip_xssi(wrapped).startswith("[[")
