"""The Python notices name what the frozen binaries ship, with each licence's id and text."""

import os
from importlib.metadata import Distribution, PackageNotFoundError
from pathlib import Path

import pytest
from notices.distribution_notice import python_notices
from notices.frozen_runtime import interpreter_notice
from notices.shipped_requirements import shipped_names

pytestmark = pytest.mark.unit

EXPORT = """\
# This file was autogenerated by uv via the following command:
#    uv export --frozen --no-dev
-e ../../plugins/core/manifest
anyio==4.15.0
    # via httpx
colorama==0.4.6 ; sys_platform == 'win32'
torch==2.9.0 ; sys_platform != 'win32'
Pillow==12.0.0
"""


class FakeDistribution(Distribution):
    """An installed distribution laid out in a folder, as pip leaves one."""

    def __init__(self, root: Path, name: str, metadata: str, files: dict[str, str]):
        self.root = root
        self.info = f"{name}-1.0.dist-info"
        for relative, text in files.items():
            path = root / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
        record = "".join(f"{relative},,\n" for relative in files)
        self.texts = {"METADATA": metadata, "RECORD": record}

    def read_text(self, filename: str) -> str | None:
        if filename in self.texts:
            return self.texts[filename]
        path = self.root / self.info / filename
        return path.read_text() if path.is_file() else None

    def locate_file(self, path: str | os.PathLike[str]) -> Path:
        return self.root / path


def test_export_keeps_what_ships_here_and_drops_our_own_editable():
    """Only third-party distributions whose markers hold here are named."""
    names = shipped_names(EXPORT, {"sys_platform": "darwin"})
    assert names == ["anyio", "pillow", "torch"]


def test_export_drops_what_another_platform_ships():
    """A distribution another platform installs is left to that platform's build."""
    assert "colorama" in shipped_names(EXPORT, {"sys_platform": "win32"})
    assert "torch" not in shipped_names(EXPORT, {"sys_platform": "win32"})


def test_reads_the_licence_expression_and_the_licence_files(tmp_path):
    """PEP 639 metadata gives the id and the dist-info's licence files the text."""
    dist = FakeDistribution(
        tmp_path,
        "httpx",
        "Name: httpx\nVersion: 0.28.1\nLicense-Expression: BSD-3-Clause\n"
        "License-File: LICENSE.md\n",
        {
            "httpx-1.0.dist-info/licenses/LICENSE.md": "Copyright Encode",
            "httpx/__init__.py": "",
        },
    )
    [entry] = python_notices(["httpx"], {"httpx": dist}.__getitem__)
    assert entry["name"] == "httpx"
    assert entry["version"] == "0.28.1"
    assert entry["tree"] == "python"
    assert entry["license"] == "BSD-3-Clause"
    assert "Copyright Encode" in entry["text"]


def test_falls_back_to_the_classifier_and_a_licence_file_in_the_package(tmp_path):
    """Older wheels still yield an id and the licence file they install."""
    dist = FakeDistribution(
        tmp_path,
        "old",
        "Name: old\nVersion: 2.0\nLicense: UNKNOWN\n"
        "Classifier: License :: OSI Approved :: MIT License\n",
        {"old/COPYING": "Permission is hereby granted", "old/core.py": ""},
    )
    [entry] = python_notices(["old"], {"old": dist}.__getitem__)
    assert entry["license"] == "MIT License"
    assert "Permission is hereby granted" in entry["text"]


def test_a_licence_written_out_in_the_metadata_is_the_text(tmp_path):
    """A licence pasted into the License field is kept as the text."""
    # A folded header, as METADATA writes a long field.
    full = "Copyright (c) someone\n        Redistribution and use in source and binary forms"
    dist = FakeDistribution(
        tmp_path, "inline", f"Name: inline\nVersion: 1\nLicense: {full}\n", {}
    )
    [entry] = python_notices(["inline"], {"inline": dist}.__getitem__)
    assert "Redistribution and use" in entry["text"]


def test_a_distribution_with_no_licence_file_has_no_text_for_the_gate(tmp_path):
    """No licence file leaves the text empty, so the merge gate can catch it."""
    dist = FakeDistribution(
        tmp_path, "bare", "Name: bare\nVersion: 1\nLicense: MIT\n", {"bare/x.py": ""}
    )
    [entry] = python_notices(["bare"], {"bare": dist}.__getitem__)
    assert entry["license"] == "MIT"
    assert entry["text"] == ""


def test_a_name_that_is_not_installed_is_an_entry_the_gate_catches():
    """A shipped name missing here fails the gate instead of vanishing."""

    def missing(name: str) -> Distribution:
        raise PackageNotFoundError(name)

    [entry] = python_notices(["ghost"], missing)
    assert entry["text"] == ""
    assert "not installed" in entry["note"].lower()


def test_the_frozen_interpreter_ships_its_own_licence():
    """CPython's own licence covers the interpreter both binaries carry."""
    entry = interpreter_notice()
    assert entry["license"] == "PSF-2.0"
    assert "PYTHON SOFTWARE FOUNDATION LICENSE" in entry["text"]


def test_a_latin_1_licence_file_is_read_not_fatal(tmp_path):
    """A licence file that is not UTF-8 is still read."""
    dist = FakeDistribution(
        tmp_path, "aged", "Name: aged\nVersion: 1\nLicense: BSD\n", {"aged/x.py": ""}
    )
    (tmp_path / "aged" / "LICENSE").write_bytes("Copyright \xa9 1999".encode("latin-1"))
    dist.texts["RECORD"] += "aged/LICENSE,,\n"
    [entry] = python_notices(["aged"], {"aged": dist}.__getitem__)
    assert entry["text"] == "Copyright \xa9 1999"
