name: Docs
description: Something in the docs is wrong or missing
title: "[docs] "
labels: [documentation]
body:
  - type: input
    id: where
    attributes:
      label: Where?
      description: A file or a URL
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: What should it say?
    validations:
      required: true
