/** Sample chart data for Remotion Studio preview. */
import type { ChartSceneInput } from "./types";

export const DEMO_CHART: ChartSceneInput = {
  type: "chart",
  title: "Quarterly Revenue",
  subtitle: "Revenue by product line (in millions)",
  items: [
    { label: "Cloud", value: 42, color: "#6c7dff" },
    { label: "SaaS", value: 35, color: "#00c9a7" },
    { label: "Enterprise", value: 28, color: "#ff6b6b" },
    { label: "Mobile", value: 22, color: "#ffd93d" },
    { label: "IoT", value: 18, color: "#c084fc" },
    { label: "AI/ML", value: 31, color: "#f97316" },
    { label: "Security", value: 15, color: "#14b8a6" },
  ],
};

/** 20 items — triggers overflow & camera paging for horizontal bar charts. */
export const DEMO_CHART_LARGE: ChartSceneInput = {
  type: "chart",
  title: "Top 20 Markets",
  subtitle: "Annual revenue by region (in millions)",
  items: [
    { label: "North America", value: 65, color: "#6c7dff" },
    { label: "Europe", value: 52, color: "#00c9a7" },
    { label: "Asia Pacific", value: 48, color: "#ff6b6b" },
    { label: "Latin America", value: 34, color: "#ffd93d" },
    { label: "Middle East", value: 29, color: "#c084fc" },
    { label: "Africa", value: 22, color: "#f97316" },
    { label: "Oceania", value: 19, color: "#14b8a6" },
    { label: "Southeast Asia", value: 38, color: "#e879f9" },
    { label: "Eastern Europe", value: 26, color: "#38bdf8" },
    { label: "Central Asia", value: 15, color: "#a3e635" },
    { label: "Nordics", value: 21, color: "#fb923c" },
    { label: "Iberian", value: 17, color: "#f472b6" },
    { label: "South Asia", value: 33, color: "#2dd4bf" },
    { label: "Caribbean", value: 12, color: "#818cf8" },
    { label: "Sub-Saharan", value: 9, color: "#fbbf24" },
    { label: "Balkans", value: 14, color: "#34d399" },
    { label: "Scandinavia", value: 24, color: "#a78bfa" },
    { label: "Benelux", value: 20, color: "#f87171" },
    { label: "Indochina", value: 27, color: "#22d3ee" },
    { label: "Polynesia", value: 8, color: "#facc15" },
  ],
};

/** 35 items — triggers overflow & camera paging for column and line charts (wider viewport). */
export const DEMO_CHART_XL: ChartSceneInput = {
  type: "chart",
  title: "Global Technology Index",
  subtitle: "Innovation score by country",
  items: [
    { label: "USA", value: 95, color: "#6c7dff" },
    { label: "China", value: 88, color: "#00c9a7" },
    { label: "Japan", value: 82, color: "#ff6b6b" },
    { label: "Germany", value: 79, color: "#ffd93d" },
    { label: "UK", value: 76, color: "#c084fc" },
    { label: "S.Korea", value: 85, color: "#f97316" },
    { label: "France", value: 73, color: "#14b8a6" },
    { label: "Canada", value: 71, color: "#e879f9" },
    { label: "India", value: 68, color: "#38bdf8" },
    { label: "Australia", value: 66, color: "#a3e635" },
    { label: "Israel", value: 80, color: "#fb923c" },
    { label: "Sweden", value: 74, color: "#f472b6" },
    { label: "Singapore", value: 78, color: "#2dd4bf" },
    { label: "Taiwan", value: 77, color: "#818cf8" },
    { label: "Netherlands", value: 72, color: "#fbbf24" },
    { label: "Switzerland", value: 75, color: "#34d399" },
    { label: "Finland", value: 69, color: "#a78bfa" },
    { label: "Denmark", value: 67, color: "#f87171" },
    { label: "Norway", value: 65, color: "#22d3ee" },
    { label: "Ireland", value: 63, color: "#facc15" },
    { label: "Austria", value: 60, color: "#6c7dff" },
    { label: "Belgium", value: 58, color: "#00c9a7" },
    { label: "Spain", value: 55, color: "#ff6b6b" },
    { label: "Italy", value: 54, color: "#ffd93d" },
    { label: "Poland", value: 50, color: "#c084fc" },
    { label: "Brazil", value: 48, color: "#f97316" },
    { label: "Mexico", value: 44, color: "#14b8a6" },
    { label: "Turkey", value: 42, color: "#e879f9" },
    { label: "Thailand", value: 40, color: "#38bdf8" },
    { label: "Malaysia", value: 45, color: "#a3e635" },
    { label: "Vietnam", value: 38, color: "#fb923c" },
    { label: "Indonesia", value: 36, color: "#f472b6" },
    { label: "Philippines", value: 33, color: "#2dd4bf" },
    { label: "Chile", value: 46, color: "#818cf8" },
    { label: "Argentina", value: 41, color: "#fbbf24" },
  ],
};
