"""Add GITHUB_CONNECTOR to SearchSourceConnectorType enum

Revision ID: 1
Revises:

"""

from collections.abc import Sequence

from alembic import op

# Import pgvector if needed for other types, though not for this ENUM change
# import pgvector


# revision identifiers, used by Alembic.
revision: str = "1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Manually add the command to add the enum value
    # Note: It's generally better to let autogenerate handle this, but we're bypassing it
    op.execute(
        """
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_enum
        WHERE enumlabel = 'GITHUB_CONNECTOR'
        AND enumtypid = (
            SELECT oid FROM pg_type WHERE typname = 'searchsourceconnectortype'
        )
    ) THEN
        ALTER TYPE searchsourceconnectortype ADD VALUE 'GITHUB_CONNECTOR';
    END IF;
END$$;
"""
    )

    # Pass for the rest, as autogenerate didn't run to add other schema details
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Downgrading removal of an enum value is complex and potentially dangerous
    # if the value is in use. Often omitted or requires manual SQL based on context.
    # For now, we'll just pass. If you needed to reverse this, you'd likely
    # have to manually check if 'GITHUB_CONNECTOR' is used in the table
    # and then potentially recreate the type without it.
    op.execute(
        "ALTER TYPE searchsourceconnectortype RENAME TO searchsourceconnectortype_old"
    )
    op.execute(
        "CREATE TYPE searchsourceconnectortype AS ENUM('SERPER_API', 'TAVILY_API', 'SLACK_CONNECTOR', 'NOTION_CONNECTOR')"
    )
    op.execute(
        "ALTER TABLE search_source_connectors ALTER COLUMN connector_type TYPE searchsourceconnectortype USING "
        "connector_type::text::searchsourceconnectortype"
    )
    op.execute("DROP TYPE searchsourceconnectortype_old")

    pass
    # ### end Alembic commands ###
