"""add inference_params to searchspaces 3

Revision ID: b86972495f7d
Revises: 2c3ace3296c0
Create Date: 2025-10-05 15:05:06.391825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86972495f7d'
down_revision: Union[str, None] = '2c3ace3296c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('chucks_search_index'), table_name='chunks', postgresql_using='gin')
    op.drop_index(op.f('chucks_vector_index'), table_name='chunks', postgresql_using='hnsw')
    op.drop_index(op.f('document_search_index'), table_name='documents', postgresql_using='gin')
    op.drop_index(op.f('document_vector_index'), table_name='documents', postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('document_vector_index'), 'documents', ['embedding'], unique=False, postgresql_using='hnsw')
    op.create_index(op.f('document_search_index'), 'documents', [sa.literal_column("to_tsvector('english'::regconfig, content)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('chucks_vector_index'), 'chunks', ['embedding'], unique=False, postgresql_using='hnsw')
    op.create_index(op.f('chucks_search_index'), 'chunks', [sa.literal_column("to_tsvector('english'::regconfig, content)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
