packages: []

allowBuilds:
  esbuild: true
  msw: false

minimumReleaseAgeExclude:
  - react-intl@12.1.3
  - '@formatjs/cli-native-darwin-arm64@1.1.26'
  - '@formatjs/cli-native-linux-arm64-musl@1.0.24'
  - '@formatjs/cli-native-linux-arm64@1.2.26'
  - '@formatjs/cli-native-linux-x64-musl@1.0.24'
  - '@formatjs/cli-native-linux-x64@1.1.26'
  - '@formatjs/cli-native-win32-x64@1.1.27'
  - '@formatjs/cli@6.16.32'
