allowBuilds:
  "@parcel/watcher": true
  "@rocicorp/zero-sqlite3": true
  "@swc/core": true
  core-js: true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

minimumReleaseAge: 10080