export interface Language {
	value: string;
	label: string;
}

export const LANGUAGES: Language[] = [
	{ value: "English", label: "English" },
	{ value: "Spanish", label: "Spanish" },
	{ value: "French", label: "French" },
	{ value: "German", label: "German" },
	{ value: "Italian", label: "Italian" },
	{ value: "Portuguese", label: "Portuguese" },
	{ value: "Russian", label: "Russian" },
	{ value: "Chinese", label: "Chinese (Simplified)" },
	{ value: "Chinese-traditional", label: "Chinese (Traditional)" },
	{ value: "Japanese", label: "Japanese" },
	{ value: "Korean", label: "Korean" },
	{ value: "Arabic", label: "Arabic" },
	{ value: "Hindi", label: "Hindi" },
	{ value: "Dutch", label: "Dutch" },
	{ value: "Swedish", label: "Swedish" },
	{ value: "Norwegian", label: "Norwegian" },
	{ value: "Danish", label: "Danish" },
	{ value: "Finnish", label: "Finnish" },
	{ value: "Polish", label: "Polish" },
	{ value: "Czech", label: "Czech" },
	{ value: "Hungarian", label: "Hungarian" },
	{ value: "Romanian", label: "Romanian" },
	{ value: "Bulgarian", label: "Bulgarian" },
	{ value: "Croatian", label: "Croatian" },
	{ value: "Serbian", label: "Serbian" },
	{ value: "Slovenian", label: "Slovenian" },
	{ value: "Slovak", label: "Slovak" },
	{ value: "Lithuanian", label: "Lithuanian" },
	{ value: "Latvian", label: "Latvian" },
	{ value: "Estonian", label: "Estonian" },
	{ value: "Greek", label: "Greek" },
	{ value: "Turkish", label: "Turkish" },
	{ value: "Hebrew", label: "Hebrew" },
	{ value: "Thai", label: "Thai" },
	{ value: "Vietnamese", label: "Vietnamese" },
	{ value: "Indonesian", label: "Indonesian" },
	{ value: "Malay", label: "Malay" },
	{ value: "Tagalog", label: "Filipino/Tagalog" },
	{ value: "Bengali", label: "Bengali" },
	{ value: "Tamil", label: "Tamil" },
	{ value: "Telugu", label: "Telugu" },
	{ value: "Marathi", label: "Marathi" },
	{ value: "Gujarati", label: "Gujarati" },
	{ value: "Kannada", label: "Kannada" },
	{ value: "Malayalam", label: "Malayalam" },
	{ value: "Punjabi", label: "Punjabi" },
	{ value: "Urdu", label: "Urdu" },
	{ value: "Persian", label: "Persian/Farsi" },
	{ value: "Swahili", label: "Swahili" },
	{ value: "Afrikaans", label: "Afrikaans" },
	{ value: "Amharic", label: "Amharic" },
	{ value: "Ukrainian", label: "Ukrainian" },
	{ value: "Belarusian", label: "Belarusian" },
	{ value: "Georgian", label: "Georgian" },
	{ value: "Armenian", label: "Armenian" },
	{ value: "Azerbaijani", label: "Azerbaijani" },
	{ value: "Kazakh", label: "Kazakh" },
	{ value: "Uzbek", label: "Uzbek" },
	{ value: "Kyrgyz", label: "Kyrgyz" },
	{ value: "Tajik", label: "Tajik" },
	{ value: "Turkmen", label: "Turkmen" },
	{ value: "Mongolian", label: "Mongolian" },
];
