/** Sample relation data for Remotion Studio preview. */
import type { RelationSceneInput } from "./types";

export const DEMO_RELATION: RelationSceneInput = {
  type: "relation",
  title: "System Architecture",
  subtitle: "Service communication flow",
  nodes: [
    { id: "api", label: "API Gateway", desc: "Load balancer & rate limiter", color: "#6c7dff" },
    { id: "auth", label: "Auth Service", desc: "OAuth 2.0 / JWT tokens", color: "#00c9a7" },
    { id: "users", label: "User Service", desc: "Profile management", color: "#ff6b6b" },
    { id: "orders", label: "Order Service", desc: "Order lifecycle", color: "#ffd93d" },
    { id: "payments", label: "Payment Service", desc: "Stripe integration", color: "#c084fc" },
    { id: "notify", label: "Notification", desc: "Email & push alerts", color: "#f97316" },
    { id: "db", label: "Database", desc: "PostgreSQL cluster", color: "#14b8a6" },
  ],
  edges: [
    { from: "api", to: "auth", label: "validates" },
    { from: "api", to: "users", label: "routes" },
    { from: "api", to: "orders", label: "routes" },
    { from: "orders", to: "payments", label: "charges" },
    { from: "orders", to: "notify", label: "triggers" },
    { from: "users", to: "db", label: "reads/writes" },
    { from: "orders", to: "db", label: "reads/writes" },
    { from: "auth", to: "db", label: "checks" },
  ],
};

export const DEMO_RELATION_LARGE: RelationSceneInput = {
  type: "relation",
  title: "Microservices Mesh",
  subtitle: "15 services with inter-dependencies",
  nodes: [
    { id: "gateway", label: "API Gateway", desc: "Entry point", color: "#6c7dff" },
    { id: "auth", label: "Auth", desc: "Identity provider", color: "#00c9a7" },
    { id: "users", label: "Users", desc: "User profiles", color: "#ff6b6b" },
    { id: "products", label: "Products", desc: "Catalog service", color: "#ffd93d" },
    { id: "orders", label: "Orders", desc: "Order processing", color: "#c084fc" },
    { id: "payments", label: "Payments", desc: "Billing engine", color: "#f97316" },
    { id: "inventory", label: "Inventory", desc: "Stock tracking", color: "#14b8a6" },
    { id: "shipping", label: "Shipping", desc: "Logistics API", color: "#e879f9" },
    { id: "analytics", label: "Analytics", desc: "Event streaming", color: "#38bdf8" },
    { id: "search", label: "Search", desc: "Elasticsearch", color: "#a3e635" },
    { id: "cache", label: "Cache", desc: "Redis cluster", color: "#fb923c" },
    { id: "queue", label: "Message Queue", desc: "RabbitMQ", color: "#f472b6" },
    { id: "storage", label: "Object Storage", desc: "S3 compatible", color: "#2dd4bf" },
    { id: "logging", label: "Logging", desc: "ELK stack", color: "#818cf8" },
    { id: "config", label: "Config Service", desc: "Feature flags", color: "#fbbf24" },
  ],
  edges: [
    { from: "gateway", to: "auth" },
    { from: "gateway", to: "users" },
    { from: "gateway", to: "products" },
    { from: "gateway", to: "orders" },
    { from: "orders", to: "payments" },
    { from: "orders", to: "inventory" },
    { from: "orders", to: "shipping" },
    { from: "orders", to: "queue" },
    { from: "products", to: "search" },
    { from: "products", to: "cache" },
    { from: "analytics", to: "queue" },
    { from: "shipping", to: "queue" },
    { from: "users", to: "storage" },
    { from: "auth", to: "cache" },
    { from: "logging", to: "storage" },
    { from: "config", to: "gateway" },
    { from: "config", to: "auth" },
  ],
};

export const DEMO_RELATION_XL: RelationSceneInput = {
  type: "relation",
  title: "Enterprise Platform",
  subtitle: "25-service cloud-native architecture",
  nodes: [
    { id: "lb", label: "Load Balancer", desc: "HAProxy / Nginx ingress", color: "#6c7dff" },
    { id: "gateway", label: "API Gateway", desc: "Rate limiting & routing", color: "#818cf8" },
    { id: "auth", label: "Auth Service", desc: "OAuth 2.0 / SAML / MFA", color: "#00c9a7" },
    { id: "iam", label: "IAM", desc: "Role-based access control", color: "#2dd4bf" },
    { id: "users", label: "User Service", desc: "Profile & preferences", color: "#ff6b6b" },
    { id: "teams", label: "Team Service", desc: "Org management", color: "#f87171" },
    { id: "products", label: "Product Catalog", desc: "Inventory listing", color: "#ffd93d" },
    { id: "pricing", label: "Pricing Engine", desc: "Dynamic pricing rules", color: "#fbbf24" },
    { id: "orders", label: "Order Service", desc: "Order lifecycle mgmt", color: "#c084fc" },
    { id: "cart", label: "Cart Service", desc: "Shopping cart state", color: "#a78bfa" },
    { id: "payments", label: "Payment Service", desc: "Stripe / PayPal", color: "#f97316" },
    { id: "billing", label: "Billing", desc: "Invoice generation", color: "#fb923c" },
    { id: "inventory", label: "Inventory", desc: "Warehouse stock sync", color: "#14b8a6" },
    { id: "shipping", label: "Shipping", desc: "FedEx / UPS / DHL", color: "#e879f9" },
    { id: "returns", label: "Returns", desc: "RMA processing", color: "#d946ef" },
    { id: "notifications", label: "Notifications", desc: "Email / SMS / Push", color: "#f472b6" },
    { id: "search", label: "Search", desc: "Full-text search index", color: "#a3e635" },
    { id: "recommendations", label: "Recommendations", desc: "ML-based suggestions", color: "#84cc16" },
    { id: "analytics", label: "Analytics", desc: "Real-time dashboards", color: "#38bdf8" },
    { id: "queue", label: "Message Queue", desc: "Kafka / RabbitMQ", color: "#f472b6" },
    { id: "cache", label: "Cache Layer", desc: "Redis + CDN edge", color: "#fb923c" },
    { id: "db", label: "Primary DB", desc: "PostgreSQL cluster", color: "#64748b" },
    { id: "docdb", label: "Document DB", desc: "MongoDB replica set", color: "#94a3b8" },
    { id: "storage", label: "Object Storage", desc: "S3 / MinIO buckets", color: "#2dd4bf" },
    { id: "monitoring", label: "Monitoring", desc: "Prometheus + Grafana", color: "#818cf8" },
  ],
  edges: [
    { from: "lb", to: "gateway" },
    { from: "gateway", to: "auth" },
    { from: "gateway", to: "users" },
    { from: "gateway", to: "products" },
    { from: "gateway", to: "orders" },
    { from: "gateway", to: "cart" },
    { from: "gateway", to: "search" },
    { from: "auth", to: "iam" },
    { from: "auth", to: "cache" },
    { from: "iam", to: "db" },
    { from: "users", to: "teams" },
    { from: "users", to: "db" },
    { from: "products", to: "pricing" },
    { from: "products", to: "search" },
    { from: "products", to: "recommendations" },
    { from: "products", to: "docdb" },
    { from: "cart", to: "orders" },
    { from: "orders", to: "payments" },
    { from: "orders", to: "inventory" },
    { from: "orders", to: "shipping" },
    { from: "orders", to: "notifications" },
    { from: "orders", to: "queue" },
    { from: "payments", to: "billing" },
    { from: "payments", to: "db" },
    { from: "shipping", to: "returns" },
    { from: "shipping", to: "notifications" },
    { from: "billing", to: "notifications" },
    { from: "inventory", to: "db" },
    { from: "analytics", to: "queue" },
    { from: "analytics", to: "docdb" },
    { from: "recommendations", to: "analytics" },
    { from: "notifications", to: "queue" },
    { from: "monitoring", to: "queue" },
    { from: "search", to: "cache" },
    { from: "storage", to: "monitoring" },
  ],
};
