name: Backend CI/CD

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'surfsense_backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'surfsense_backend/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: ankane/pgvector:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: surfsense_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip uv
          cd surfsense_backend
          python -m venv .venv
          source .venv/bin/activate
          uv pip sync
          
      - name: Run linters
        run: |
          cd surfsense_backend
          source .venv/bin/activate
          ruff check .
          
      - name: Run tests
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/surfsense_test
        run: |
          cd surfsense_backend
          source .venv/bin/activate
          pytest 